import pygame

TITLE = "PRI Game"

SCREEN_WIDTH, SCREEN_HEIGHT = 640, 480

FPS = 90

### DOT ###
DOT_SIZE = 15
DOT_HIT_SIZE = (DOT_SIZE+10, DOT_SIZE+10)
### TARGET ###
TARGET_SIZE = (60, 30)
TARGET_SIZE_RANDOM = (1, 2)
TARGET_SPAWN_TIME = 3
TARGET_HIT_SIZE = (TARGET_SIZE[0]-10, TARGET_SIZE[1]-10)
### BULLET ###
BULLET = 20
